blank_issues_enabled: false
contact_links:
  - name: GameMaker Feature Requests
    url: https://github.com/YoYoGames/GameMaker-Bugs/issues/new?assignees=&labels=feature+request&projects=&template=feature-request.yml
    about: Suggest an improvement for GameMaker!
  - name: GameMaker Account Support
    url: https://contact.gamemaker.io/contact-us
    about: Contact the Helpdesk if you're having trouble with your GameMaker account.
  - name: GameMaker Bug Reports
    url: https://contact.gamemaker.io/contact-us#bug
    about: Report a GameMaker bug

    
